language:
- ruby
before_install:
- gem update --system
- gem install bundler
install:
- bundle install
cache:
- bundler
script:
- LOG_LEVEL=error bundle exec rspec -fd
deploy:
- provider: lambda
  function_name: RecapHoldRequestConsumer-qa
  description: A consumer for handling hold requests from ReCAP.
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  module_name: main
  handler_name: handle_event
  timeout: 60
  environment_variables:
  - TIME_ZONE=America/New_York
  - ENCODED_NCIP_URL=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJowgZcGCSqGSIb3DQEHBqCBiTCBhgIBADCBgAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAydD8EKFnoYquS7udMCARCAU4bgcPpxw4Jw+5zVNLdFUM8db3eHbyJXcz3WphVnyTWhCFQ/a5Rdf5wUzzLU5fQKlFX5pEmcsjq87sS47rcnky/RdgI0w8OZmFRFDlmEL73wCC6a
  - SIERRA_URL=https://nypl-sierra-test.nypl.org/iii/sierra-api/v4
  - ENCODED_RECAP_CLIENT_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxYYmZ81QcHmUMeCmwCARCAQ8rkJmRUh4DoKF7Spptxhi0YCEoWTk6goN0YumQbgwuSzEu58pZXrxWmkKC9nFcGYCz7tCkObn2lL6kAbSuUFxnKOLc=
  - ENCODED_SIERRA_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCqIWLz/fIFg3+8DTwIBEIA33va31Ub2pNjh/s2eNtgWypFLMwfGpo+d7kKTmT/jq81t683Parg2cRj2pUxcdaCKHEueUMmQCw==
  - ENCODED_SIERRA_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAG0wawYJKoZIhvcNAQcGoF4wXAIBADBXBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJhykLjDmrnUaYtiWwIBEIAqMSqP3kL/qg2IGqMqWfS9BmZJWzL0wJN/SkKcAwlEWPy1QUlJolPDD0rf
  - RECAP_HOLD_REQUEST_AUTH_URL=https://isso.nypl.org/oauth/token
  - RECAP_CLIENT_ID=recap_hold_request_consumer
  - HOLD_REQUESTS_URL=https://qa-platform.nypl.org/api/v0.1
  - HOLD_REQUEST_RESULT_STREAM=HoldRequestResult-qa
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
notifications:
  email:
    on_failure: always
env:
  global:
    secure: ZP8sP3dG646MmFakzB8FEyQh5qYWtMTwpwfW+nDYYadeaEDeykIodqgwWiM7ZT10w3Y2QYMzUsuVp7ghdFr7BWRQEoDFf4vC+aFDesNcsIk14Zl2QG4u8OPEuY3EDnh9ONAuF5AqsSMcVTa7geFuRfA0V587Xdnfrfbn7zRZ1WFpzR/NiNeixELn6pJHlu/qcs05M9vBgcvClLfYodpVLbU5Hf9ZAchgrzRc9oWrOvWySs9tViLiImOzbHpIv/5CQ9hEYtalJlo3fGWlyAzmBJ9QUFCafEsr12/0w5cyOBCBo774ngDPxcMt9fojkDE5ofKtBLSzovs1B/TcHTFNThhCBv7HfjaWYE+50z9Y+HiytshqcL/ovzz0YY4kaQg9N48gzNrUUZgWLGqSR62AQepaZb5BjiWvG+csKkPAtku77OlJ7xCT41GnNdSs02Eup45M7ioDuavsU0ewEvC0+Yxm02jaqoyOY4RGWofpIHAHDsxkCbBc/ffD59oCMSDQkDV7p713IwooF2mWvgLAVxkisJmj9GH+flBE+ocqyEU+F1m0xdpUHHzG+nv+cvFjZDxyK5qPnSuA1iR/9950OAVEurGUxY+J6jA/LOMBrfo2Ifj+tU8mdaY3QxCLyEX8tQlQIB86m1stvL9FblHZ4zhsHGvC817sMpzH0Bt7KC4=
