language:
- ruby
before_install:
- gem update --system
- gem install bundler
install:
- bundle install
cache:
- bundler
script:
- LOG_LEVEL=error bundle exec rspec -fd
notifications:
  email:
    on_failure: always

