language:
- ruby
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --deployment
cache:
- bundler
script:
- LOG_LEVEL=error bundle exec rspec -fd
deploy:
- provider: lambda
  function_name: RecapHoldRequestConsumer-qa
  description: A consumer for handling hold requests from ReCAP.
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  module_name: main
  handler_name: handle_event
  timeout: 60
  environment_variables:
  - TIME_ZONE=America/New_York
  - ENCODED_NCIP_URL=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJowgZcGCSqGSIb3DQEHBqCBiTCBhgIBADCBgAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAydD8EKFnoYquS7udMCARCAU4bgcPpxw4Jw+5zVNLdFUM8db3eHbyJXcz3WphVnyTWhCFQ/a5Rdf5wUzzLU5fQKlFX5pEmcsjq87sS47rcnky/RdgI0w8OZmFRFDlmEL73wCC6a
  - SIERRA_URL=https://nypl-sierra-test.nypl.org/iii/sierra-api/v4
  - ENCODED_RECAP_CLIENT_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxYYmZ81QcHmUMeCmwCARCAQ8rkJmRUh4DoKF7Spptxhi0YCEoWTk6goN0YumQbgwuSzEu58pZXrxWmkKC9nFcGYCz7tCkObn2lL6kAbSuUFxnKOLc=
  - ENCODED_SIERRA_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCqIWLz/fIFg3+8DTwIBEIA33va31Ub2pNjh/s2eNtgWypFLMwfGpo+d7kKTmT/jq81t683Parg2cRj2pUxcdaCKHEueUMmQCw==
  - ENCODED_SIERRA_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAG0wawYJKoZIhvcNAQcGoF4wXAIBADBXBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJhykLjDmrnUaYtiWwIBEIAqMSqP3kL/qg2IGqMqWfS9BmZJWzL0wJN/SkKcAwlEWPy1QUlJolPDD0rf
  - RECAP_HOLD_REQUEST_AUTH_URL=https://isso.nypl.org/oauth/token
  - RECAP_CLIENT_ID=recap_hold_request_consumer
  - HOLD_REQUESTS_URL=https://qa-platform.nypl.org/api/v0.1
  - HOLD_REQUEST_RESULT_STREAM=HoldRequestResult-qa
  - LOCATIONS_URL=https://nypl-core-objects-mapping-qa.s3.amazonaws.com/by_recap_customer_code.json
  - DEFAULT_LOGGING_LEVEL=debug
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
- provider: lambda
  function_name: RecapHoldRequestConsumer-production
  description: A consumer for handling hold requests from ReCAP.
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  module_name: main
  handler_name: handle_event
  timeout: 60
  environment_variables:
  - TIME_ZONE=America/New_York
  - ENCODED_NCIP_URL=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAI8wgYwGCSqGSIb3DQEHBqB/MH0CAQAweAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxBvKxgEWCnR/EeayECARCAS+LB2k4Lr+b7Fqx1HG1sbF18lgGjYOxkLxehFugDitYaIfK/5pXGSGfHqfyG0TvUgPtk046NHivW5KW7Elc9H1i9BkuMkvLOUv0toA==
  - SIERRA_URL=https://ilsstaff.nypl.org/iii/sierra-api/v4
  - ENCODED_RECAP_CLIENT_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxYYmZ81QcHmUMeCmwCARCAQ8rkJmRUh4DoKF7Spptxhi0YCEoWTk6goN0YumQbgwuSzEu58pZXrxWmkKC9nFcGYCz7tCkObn2lL6kAbSuUFxnKOLc=
  - ENCODED_SIERRA_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCqIWLz/fIFg3+8DTwIBEIA33va31Ub2pNjh/s2eNtgWypFLMwfGpo+d7kKTmT/jq81t683Parg2cRj2pUxcdaCKHEueUMmQCw==
  - ENCODED_SIERRA_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAG0wawYJKoZIhvcNAQcGoF4wXAIBADBXBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJhykLjDmrnUaYtiWwIBEIAqMSqP3kL/qg2IGqMqWfS9BmZJWzL0wJN/SkKcAwlEWPy1QUlJolPDD0rf
  - RECAP_HOLD_REQUEST_AUTH_URL=https://isso.nypl.org/oauth/token
  - RECAP_CLIENT_ID=recap_hold_request_consumer
  - HOLD_REQUESTS_URL=https://platform.nypl.org/api/v0.1
  - HOLD_REQUEST_RESULT_STREAM=HoldRequestResult-production
  - LOCATIONS_URL=https://nypl-core-objects-mapping-production.s3.amazonaws.com/by_recap_customer_code.json
  - DEFAULT_LOGGING_LEVEL=info
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  on:
    branch: main
notifications:
  email:
    on_failure: always
env:
  global:
    secure: Danb7s+IU9n+xJHKDtuRUrWJmWCJlVEj1UQoyzebUQnUnvuxVjDX2bHMPz1zZxoGdKDdzT5qPvd6K3R8F6DBcH+EF2s0YdcaLfKVndBvlM2j/uXKNoFCA8IhYs5JkLQMnICy/leMsCtGcFlLF/tQNr0UIS2vy8aG09dY+7VJurcGMEGpDcz2Uxx8znW8THRaa7Y7GIi/njVfhysWXyVrlvLS4eJVsVb95vr3/btdAegdIVtNG6R9ob6l4tXUq+G6xhIqhLy2H7yzUMDRG/oimvRkn2SGN/9b/TE8uC50ZTee9Ixq7PDUfJXpNQgH2dakLI5WOqd0ET81Z3XGhmkc8KXtpuCkCdNOFpVgtWddtzTc/mBqNNTUJ15G+jFFcZf9HuGXZzaCej/fRnw4GBIF9e8IaghjmBL/qaedtayMPtNnD0v/JQw39EPOYbCg9tKvT/sV3fFQFqvSkU2tBSfsSLDd5/sqeUZBo8HN+//dCxZnNd6iZT1WJJQz4dt1X3tQFxcAA7C4694pLowjz2VxIzvH/NzcyiqlSAUEYs++n0jVoW2mLdWe1Hx3Lc2wTZLltKlOMYapaeMFsdaUvew0gvahSQfQZIqNbAPn5COQowWU/jiK/d05AghAQhRQrmc4Uda5f6/AV8K1y+9F1uzwmItYAps3E0ozuqeF3XajYsc=
