source 'https://rubygems.org'

gem 'httparty'
gem 'dotenv'
gem 'faker'
gem 'json', '1.8.2'
gem 'aws-sdk', '~> 2'
gem 'aws-kclrb'
gem 'faraday'
gem 'faraday_middleware'
gem 'avro'
gem 'require_all'
gem 'rspec'
gem 'simplecov'
gem 'pry'
gem 'avromatic'
gem 'avro-patches'
gem 'oauth'
gem 'rubocop', require: false
gem 'gibberish'
