AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'recap-hold-request-consumer'

Resources:
  RecapHoldRequestConsumer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handle_event
      Runtime: ruby2.5
      Timeout: 30
      Environment:
        Variables:
          TIME_ZONE: America/New_York
          ENCODED_NCIP_URL: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJowgZcGCSqGSIb3DQEHBqCBiTCBhgIBADCBgAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAydD8EKFnoYquS7udMCARCAU4bgcPpxw4Jw+5zVNLdFUM8db3eHbyJXcz3WphVnyTWhCFQ/a5Rdf5wUzzLU5fQKlFX5pEmcsjq87sS47rcnky/RdgI0w8OZmFRFDlmEL73wCC6a
          SIERRA_URL: https://nypl-sierra-test.nypl.org/iii/sierra-api/v4
          ENCODED_RECAP_CLIENT_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxYYmZ81QcHmUMeCmwCARCAQ8rkJmRUh4DoKF7Spptxhi0YCEoWTk6goN0YumQbgwuSzEu58pZXrxWmkKC9nFcGYCz7tCkObn2lL6kAbSuUFxnKOLc=
          ENCODED_SIERRA_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHoweAYJKoZIhvcNAQcGoGswaQIBADBkBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCqIWLz/fIFg3+8DTwIBEIA33va31Ub2pNjh/s2eNtgWypFLMwfGpo+d7kKTmT/jq81t683Parg2cRj2pUxcdaCKHEueUMmQCw==
          ENCODED_SIERRA_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAG0wawYJKoZIhvcNAQcGoF4wXAIBADBXBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJhykLjDmrnUaYtiWwIBEIAqMSqP3kL/qg2IGqMqWfS9BmZJWzL0wJN/SkKcAwlEWPy1QUlJolPDD0rf
          RECAP_HOLD_REQUEST_AUTH_URL: https://isso.nypl.org/oauth/token
          RECAP_CLIENT_ID: recap_hold_request_consumer
          HOLD_REQUESTS_URL: https://qa-platform.nypl.org/api/v0.1
          HOLD_REQUEST_RESULT_STREAM: HoldRequestResult-qa
