def set_env
  ENV['SIERRA_URL'] =
  ENV['ENCODED_SIERRA_ID'] =
  ENV['ENCODED_SIERRA_SECRET'] =
  ENV['ENCODED_RECAP_CLIENT_SECRET'] =
  ENV['RECAP_HOLD_REQUEST_AUTH_URL'] =
  ENV['RECAP_CLIENT_ID'] =
  ENV['OLD_RECAP_CLIENT_SECRET'] =
  ENV['HOLD_REQUESTS_URL'] =
  ENV['HOLD_REQUEST_RESULT_STREAM'] =
  ENV['LOCATIONS_URL'] =
  ENV['NCIP_URL'] = 
end
